### ISSUE TITLE
BLU1 - Learning Notebook 1/2 Pandas for Timeseries: TypeError with astype

### ISSUE THREAD

**Issue by orlandocosta76** [LDSSA/batch2-BLU01#1]
Hi, when executing this to convert date64 to int:
`dev_time = inferred_dates.astype(int)  # our inferred dates were datetime objects, remember? 
dev_time`

I get this error:
`TypeError: cannot astype a datetimelike from [datetime64[ns]] to [int32]`

but I get by if I change to:
`pd.to_numeric(inferred_dates,  downcast='integer')`

is it some problem related to a newer version of python or pandas?

**Comment by joaobcampos** [comment]
I got by it using:
 dev_time = inferred_dates.astype('int64').

Mind the inverted commas.

**Comment by orlandocosta76** [comment]
Ok, thanks, so I was used that `astype` worked with type without quotes (and still works, for instance with str), but in this case maybe because of this different types in Python, Pandas and Numpy, as stated here:
[http://pbpython.com/pandas_dtypes.html](url)

it does not accept plain `int`, since the type of the date column is `datetime64` and the conversion would have to be made to `int64` explicitly.

**Comment by echo66** [comment]
@orlandocosta76 is it solved?

**Comment by orlandocosta76** [comment]
@echo66  Well, my assumption would be that the issue is solved when the notebook is corrected, right? Or is the procedure to just reference the problems in the issues tab, and then the original notebooks are never changed?

**Comment by PedroGFonseca** [comment]
@orlandocosta76 interesting, so it actually doesn't run in your case? 

If so, can you print the following and send me the output? 
```
import sys
print(pd.__version__)
print(np.__version__)
print(sys.version)
```

Mine is 
```
0.22.0
1.14.2
3.6.5 (default, Mar 30 2018, 06:41:53) 
```
To use that amazing phrase, it currently "runs on my machine"

**Comment by orlandocosta76** [comment]
@PedroGFonseca  I get a different version of Python:
```
0.22.0
1.14.2
3.5.5 |Anaconda, Inc.| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)]
```
Not sure if it accounts for difference...I also ran this on a Jupyter Notebook after selecting the _ldsa_ environment that was suggested for the bootcamp setup. 

@echo66 Do you have the same version as mine?

**Comment by pma2** [comment]
Does not work: dev_time = inferred_dates.astype(int)
Works: dev_time = inferred_dates.astype("int64")

#print(sys.version):
0.22.0
1.14.0
3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]

**Comment by hershaw** [comment]
@PedroGFonseca you're version of python is one minor version ahead of the official class one: it should be 3.5 rather than 3.6.

Not sure if this actually solves the problem or not though.

@orlandocosta76 where exactly in the notebook is the error?

**Comment by orlandocosta76** [comment]
@hershaw  It's on file 
[BLU1 - Learning Notebook - Part 1 of 2 - Pandas for Timeseries.ipynb](https://github.com/LDSSA/batch2-BLU01/blob/master/Learning%20Notebooks/BLU1%20-%20Learning%20Notebook%20-%20Part%201%20of%202%20-%20Pandas%20for%20Timeseries.ipynb)

just 2 code cells before the section **Selecting**, but better if you search for:

_Well fear not, Pandas has got you covered._

`dev_time = inferred_dates.astype(int)  # our inferred dates were datetime objects, remember? `
