### ISSUE TITLE
Description of labels is not correct in the second notebook 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/batch2-BLU01#3]
In the second learning notebook, where it states _"It has labels, which contains the data (prices, quality)"_ it should evidently read _"It has labels, which connect the observations with the labels"_

To illustrate this better, take the following example: 
```

data = {
    'name': {0: 'Apple', 1: 'Pear'},
    'color': {0: 'Red', 1: 'Yellow'},
    'price': {0: 1, 1: 2},
    'type': {0: 'fruit', 1: 'fruit'}
}

tiny_df = pd.DataFrame(data)
tiny_df = tiny_df.set_index(['type', 'color'])
print(tiny_df.index)
```

Which yields the following: 

`MultiIndex(levels=[['fruit'], ['Red', 'Yellow']],
           labels=[[0, 0], [0, 1]],
           names=['type', 'color'])
`

**Comment by orlandocosta76** [comment]
@PedroGFonseca By the way, if you have a single dataframe, one can check the datatype of the index by stating:
`df.index.dtype `which could yield something like `dtype('int64')`

but with a multi-index the return is not very helpful:
tiny_df.index.dtype ->  `dtype('O')`

is there any other way?
