### ISSUE TITLE
Q2 Most recent day

### ISSUE THREAD

**Issue by antoniopleite** [LDSSA/batch2-BLU01#4]
Although i have data in December 6th 2015, the most recent day that the assert is checking is July 31st 2015. Can someone help me with this?

**Comment by dominguezmaria** [comment]
Hi Antonio!
That assert is checking if the store you selected is the correct one, and for that it's using the (random day) July 31st 2015. You don't have to worry about that, just focus on answering the question and if you pass the assert, everything should be fine.

**Comment by dominguezmaria** [comment]
Hint: check the first question again and make sure that you read the hint there very carefully!
